-- ----------------------
-- sauvegarde de la base book au 25-May-2017
-- ----------------------


-- -----------------------------
-- creation de la table book
-- -----------------------------
CREATE TABLE `book` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `titre` varchar(255) CHARACTER SET latin1 NOT NULL,
  `auteur` varchar(255) CHARACTER SET latin1 NOT NULL,
  `annee` varchar(255) CHARACTER SET latin1 NOT NULL,
  `theme` varchar(255) CHARACTER SET latin1 NOT NULL,
  `resume` varchar(5000) NOT NULL,
  `tome` int(10) NOT NULL,
  `page` varchar(255) DEFAULT NULL,
  `format` varchar(255) NOT NULL,
  `date_lecture` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=95 DEFAULT CHARSET=utf8;



-- -----------------------------
-- insertions dans la table book
-- -----------------------------
INSERT INTO book VALUES('5', 'Eragon T1', 'Christopher Paolini', ' 2004 ', 'Fantasy', 'Eragon mene une vie simple, jusqu au jour ou il ramasse dans la foret une etrange pierre bleue. Le garcon decouvre qu il s agit d un oeuf et assiste bientot a la naissance...d un dragon! En decidant de l elever, il devient Dragonnier, heritier d une caste d elite que le terrible roi Galbatorix veut eliminer. Eragon n a que seize ans, mais le destin du royaume de l Alagaesia est entre ses mains. ', '1', '694', 'papier/numerique', '2014');
INSERT INTO book VALUES('6', 'Harry Potter a l ecole des sorciers T1', 'J K Rowling', ' 1997 ', 'Fantastique', ' Il s agit d une serie de sept romans racontant la jeunesse d un sorcier, Harry Potter, orphelin eleve par une famille ordinaire, les Dursley qui traitent Harry comme leur esclave plutot que comme leur neveu, et qui decouvre progressivement son identite de sorcier, son heritage tragique et la responsabilite qui lui revient. ', '1', '232', 'papier/numerique', '2009');
INSERT INTO book VALUES('7', 'Percy Jackson et le voleur de foudre T1', 'Rick Riordan', ' 2005 ', 'Fantasy', 'Attaque par sa prof de maths qui est en fait un monstre mythologique, injustement renvoye de son college et poursuivi par un minotaure enrage, Percy Jackson se retrouve en plus accuse d avoir derobe l eclair de Zeus ! Pour rester en vie, s innocenter et decouvrir l identite du dieu qui l a engendre, il devra accomplir sa quete au prix de mille dangers.
', '1', '480', 'papier/numerique', '2015');
INSERT INTO book VALUES('8', 'Donjon de Naheulbeuk a l aventure, compagnons T1', 'John Lang', ' 2001 ', 'Heroic-Fantasy / Humour ', 'Plusieurs personnages typiques des jeux de role se lancent dans une quete pour retrouver une prophetique statuette dans un donjon egalement archetypique, le fameux Donjon de Naheulbeuk.
La premiere saison raconte la recherche de la 12e statuette de Gladeulfeurha pour le compte du mage Gontran Theogal, qui cherche a accomplir une prophetie :
Il est ecrit dans les tablettes de Skelos que seul un Gnome des Forets du Nord unijambiste dansant a la pleine lune au milieu des douze statuettes enroulees dans du jambon ouvrira la porte de Zaral Bak et permettra l accomplissement de la prophetie.', '1', '381', 'papier', '2016');
INSERT INTO book VALUES('11', 'Une Ile ', 'Tracey Garvis Graves', ' 2012 ', 'Romance', 'Emnna Emerson n hesite pas un instant lorsque les Callahan lui proposent de se rendre aux Maldives pour donner des cours a leur fils T.J., en remission d un cancer. Mais rien ne se passe comme prevu : le jet prive a bord duquel ils ont embarque se crashe au beau milieu de l ocean Indien. Les voici naufrages sur une ile deserte ou ils vont devoir apprendre a survivre. Si l adolescent rechute, rien ne pourra le sauver. Anna se sent malgre tout etrangement attiree par son compagnon d infortune. Alors que chacun d eux n a plus que l autre pour unique horizon, leur seule chance de s en sortir est ce lien precieux qui ne cesse de grandir entre eux.', '1', '408', 'papier/numerique', '2016');
INSERT INTO book VALUES('10', 'Night World T1', 'L J Smith', ' 2009 ', 'Fantasy Romance', 'Il n y a plus aucun espoir pour Poppy: sa maladie est incurable. Elle se prepare donc au pire. Jusqu a ce que James, le plus beau garcon du lycee qu elle aime en secret, lui fasse le plus fabuleux des cadeaux: un baiser vertigineux qui lui donne acces a son ame. Elle apprend ainsi que James partage ses sentiments depuis toujorus, mais fait partie du NIght World.
 Bravant les interdits de son monde, le jeune homme propose a Poppy de le suivre jusqu a la mort, et meme au dela. Mais il lui faudrait pour cela devenir un vampire. ', '1', '286', 'papier/numerique', '2016');
INSERT INTO book VALUES('49', 'Night World T3', 'L J Smith', '2010', 'Fantasy Romance', ' Decouvrez ce qui arrive a ceux qui enfreignent les regles... Blaise fait chavirer les coeurs. Sa beaute sombre et incandescente inspire le desir et la jalousie. Cette cruelle sorciere a le pouvoir de reduire la gent masculine en esclavage. Alors qu elle recherche une nouvelle victime, elle rencontre Eric, qui semble etre la proie parfaite. Sa cousine Thea, qui n est pas indifferente aux charmes de celui-ci, comprend ses desseins malefiques et la previent: \" Pas touche! \". Or la magie noire de Blaise est puissante. Le seul moyen pour Thea de riposter est d utiliser sa magie blanche pour ensorceler Eric en premier. Mais les lois de son monde, le Night World, sont claires : en aucun cas elle ne doit tomber amoureuse d un humain. Alors que la nuit des sorcieres approche, Thea pourra-t-elle sauver Eric des griffes de Blaise et elle-meme de ses sentiments interdits? Jamais il n a ete aussi dangereux d aimer.
', '1', '295', 'papier/numerique', '2016');
INSERT INTO book VALUES('12', 'Au Bonheur de ces dames', 'Angela Behelle ', ' 2015 ', 'Romance Erotique', 'A 18 ans, Jeremy quitte le confort douillet et protecteur de sa campagne normande pour se lancer dans de brillantes etudes litteraires a Paris.
Alors quoi de plus normal pour ce jeune homme passionne de lectures que d etre irresistiblement attire par la librairie ancienne qui se situe juste sous ses fenetres, de l autre cote de la rue ?
Intimide, hesitant, il attend, puis se decide enfin a pousser la porte. Une clochette qui tinte, un parquet qui craque sous les pas, une odeur de bois, des livres par milliers, et, aux commandes de cette boutique hors du temps, une personne qu?il ne s attendait pas a trouver la.
Un seul regard de Claudia, la voluptueuse libraire qui se cache derriere les etageres suffit pour que la vie de ce jeune puceau provincial bascule definitivement. Fascine par cette femme mysterieuse qui se propose de faire de lui un homme, Jeremy se soumet, corps et ame, a une lente et savoureuse initiation a tous les plaisirs de la chair.
Mais entrer dans l univers de Claudia signifie egalement en accepter les regles et les secrets plus nombreux qu il n y parait. Au fur et a mesure qu il penetre l intimite de sa sulfureuse maitresse, Jeremy comprend qu il a mis le doigt dans un engrenage aussi sensuel que dangereux. Il n est cependant pas certain qu il ait envie de s y soustraire. Au contraire. Son insatiable appetit d apprendre le conduit, un livre de Zola sous le bras, a en reclamer toujours plus. Au risque, peut-etre, de compromettre son avenir.', '1', '448', 'numerique', '2016');
INSERT INTO book VALUES('13', 'L Apprenti Epouventeur T1', 'Delaney Joseph', ' 2005 ', 'Fantasy', ' Thomas J. Ward, jeune garcon de presque seize ans, septieme fils d un septieme fils, est confie ? l ?eouvanteur John Gregory pour devenir apprenti dans ce dangereux metier. Pour savoir s il est courageux, l epouvanteur laisse Tom un soir, seul dans une maison hantee, avec une chandelle pour s eclairer dans le noir. De plus, il lui confie la mission de se rendre a minuit dans la cave pour y affronter la chose qui s y cache !
L epouvanteur decide de garder Thomas en periode d essai. Il emmene le garcon dans sa maison, a Chippenden (qui correspond ? la ville de Chipping, en Angleterre). La, il lui enseigne ce qu il y a faut savoir sur les gobelins ou les sorcieres, ainsi que le latin. Tout se passe bien jusqu a ce que Tom rencontre Alice, une jeune fille qui lui rend service face aux garcons du village. Elle fait fuir les voyous en leur annoncant que sa tante, Lizzie l Osseuse, est revenue aux alentours de Chipenden. Alice va alors lui demander un service en retour : donner un gateau chaque nuit a une pauvre sorciere affamee, emprisonnee dans le jardin de l epouvanteure Mais la deuxieme nuit, alors qu il vient juste de l?cher la friandise (en fait constituee de sang d Alice) Tom decouvre que les barreaux de fer qui fermaient la fosse de la sorciere ont ete tordus et se rend compte que les geteaux rendent la sorciere plus forte si bien qu elle s enfuit la deuxieme nuit. ', '1', '275', 'numerique', '2016');
INSERT INTO book VALUES('14', 'L Assassin Royal', 'Robin Hobb', '1997', 'Fantasy', 'Au chateau de Castelcerf le roi Subtil Loinvoyant regne sur les Six Duches; il est aide dans sa lourde tache par son fils Chevalerie qui, comme son pere et tous les nobles du royaume, porte le nom de la qualite que ses parents esperaient le voir developper. Ainsi le frere du Roi-servant s appelle-t-il Verite et leur demi-frere, ne d un second lit, Royal. Suite a une aventure restee inconnue de tous, Chevalerie donne a la lignee un nouveau descendant : un batard, dont la simple existence va bouleverser le fragile equilibre qu avait etabli le roi pour controler ses turbulents fils. Ce heros malgre lui, nomme Fitz, voit son avenir s assombrir au fil du temps. Alors que les autres enfants ont deja leur place a la cour et dans ses intrigues, lui devra la meriter et servir la couronne en devenant ce que personne ne voulait etre : l Assassin royal. Au service de son roi, il apprendra les poisons, le meurtre et la trahison..', '1', '416', 'papier/numerique', '2016');
INSERT INTO book VALUES('15', 'Star Wars Revan', 'Drew KARPYSHYN', '2012', 'Science Fiction', 'Il y a quelque chose la, dehors : une montagne malefique venant ecraser la Republique, a moins qu un Jedi solitaire, en fuite et injurie, ne puisse l arreter. Revan : heros, traitre, conquerant, mechant, sauveur. Un Jedi qui a quitte Coruscant pour eliminer les Madaloriens, et revenu en tant que disciple du Cote Obscur, destine a detruire la Republique. Le Conseil Jedi a rendu a Revan sa vie d avant, mais le prix de la redemption fut eleve. Ses souvenirs ont ete effaces. Seuls restent des cauchemars, et une peur profonde et permanente. Que s est-il exactement passe dans la Bordure Exterieure ? Revan ne s en souvient quasiment plus, mais ne peut pas completement oublier non plus. D une certaine facon, il se heurte a un terrible secret qui menace l existence meme de la Republique. N ayant aucune idee de ce dont il s agit, ni de la facon de l arreter, Revan pourrait tres bien echouer, car il n a jamais affronte un ennemi aussi diabolique et puissant. Mais seul la mort peut l empecher d essayer.
', '1', '376', 'papier', '2014');
INSERT INTO book VALUES('16', 'Star Wars Complots', 'Paul S Kemp', '2013', 'Science Fiction', 'Dark Malgus sert un but, la guerre, et un maitre, le Cote Obscur, pour lesquels il s apprete a mettre a feu et a sang la Cite galactique. Il a detruit le Temple Jedi de Coruscant en leurs noms, dans une bataille historique au cours de laquelle le Maitre Ven Zallow a ete assassine. Mais a l heure des machinations politiques, l Empereur n a plus besoin de son champion et cherche a le faire disparaitre...
Et il n est pas le seul. Une jeune Jedi est prete a tout pour venger la mort de son Maitre, elle s appelle Aryn Leener et elle ne reculera devant aucun sacrifice, quitte a enfreindre toutes les regles.
Deux destinees, deux revoltes vont se croiser dans une galaxie devenue l enjeu de sinistres complots...', '1', '374', 'papier', '2014');
INSERT INTO book VALUES('17', 'Star Wars Annihilation', 'Drew KARPYSHYN', '2014', 'Science Fiction', 'L Empire Sith est en plein bouleversement. L Empereur a disparu, presume mort, et la tentative de prendre possession du trone par un Seigneur Sith ambitieux s est achevee tragiquement. Neanmoins, Darth Karrid, commandant du tres craint croiseur Imperial Ascendant Spear, poursuis ses implacables efforts pour realiser son objectif : une domination totale de la galaxie par les Sith.
Mais la determination sans faille de Karrid est mise a mal par la volonte d acier de Theron Shan, dont les travaux inacheves avec l Empire pourraient changer le destin de la guerre pour le bien de tous. Bien qu il soit le fils d un Maitre Jedi, Theron n a aucune affinite avec la Force - mais tout comme sa celebre mere, l esprit de la rebellion coule dans ses veines. Sous couverture en tant qu agent de la Republique, il porte un coup crucial contre l Empire en detruisant un arsenal de super-armes Sith - ce qui lui donne l opportunite d oser une dangereuse mission ayant pour objectif de mettre fin au regne de l Ascendant Spear', '1', '416', 'papier', '2014');
INSERT INTO book VALUES('18', 'L Epee de Verite La Premiere Lecon du Sorcier T1', 'Terry GoodKing', '2003', 'Fantasy', 'Jusqu a ce que Richard Cypher sauve cette belle inconnue des griffes des ses poursuivants, il vivait paisiblement dans la foret de Hartland. Elle ne consent a lui dire que son nom: Kahlan. Des le premier regard, il sait qu il ne pourra plus jamais la quitter. Or, elle vient des Contrees du Milieu, territoire separe d Hartland par une frontiere infranchissable! Et elle n est pas venu seule. Desormais, le danger rode dans la foret. Des creatures monstrueuses suivent les pas de l etrangere.
Seul Zedd, le vieil ermite, ami de Richard, peut lui venir en aide? mais ce faisant, il risque de bouleverser le destin du jeune homme. Car Zedd n est autre que le grand sorcier, refugie en Terre d?Ouest, que Kahlan vient chercher.
Ensemble, les trois compagnons vont s opposer au tyran Darken Rahl qui regne a present sur les Contrees du Milieu. Rahl est un fou sanguinaire qui projette de detruire le monde a l aide d anciens artefacts, les boites d Orden. Pour tenter de l arreter, Zedd fait de Richard le Sourcier en lui remettant la legendaire ?pee de Verite. Cette epee lui donne le pouvoir devastateur de rendre justice, mais l arme est a double tranchant, car Richard eprouvera la souffrance de tous ceux qu il tuera?', '1', '532', 'papier/numerique', '2015');
INSERT INTO book VALUES('19', 'La Peste', 'Albert Camus', '1947', 'Existentialisme', ' L histoire se deroule dans les annees 1940. Elle a pour theatre Oran durant la periode de l Algerie francaise. Le roman raconte sous forme de chronique la vie quotidienne des habitants pendant une epidemie de peste qui frappe la ville et la coupe du monde exterieur. Camus semble s etre documente sur une petite epidemie de peste bubonique, survenue a Oran en 1945, succedant a une epidemie plus serieuse qui avait eu lieu a Alger en 1944, mais son projet est anterieur a l apparition de ces epidemies, puisqu il y travaille depuis 1942 (comme en temoignent ses Carnets).', '1', '352', 'papier/numerique', '2010');
INSERT INTO book VALUES('20', 'La Potion magique de Georges Bouillon', 'Roald Dahld', '1981', 'Jeunesse', 'La grand-mere de Georges n est pas de ces adorables mamies gateaux qui racontent des histoires et offrent des bonbons. Elle serait plutot du genre sorciere, mechante et aimant faire peur aux enfants.
Puisque c est une sorciere, Georges decide de la transformer en lui concoctant une potion magique a sa facon. Du genre explosif. Une potion qui aura des effets plutot inattendus...
C est un vrai bonheur que de suivre le petit Georges dans sa confection de la plus infame mixture qui soit, composee de tout ce que la maison contient de moins appetissant : vernis a ongles, cirage, peinture, savon, tout atterrit dans le chaudron. Le genre de tambouille que tout enfant a reve de faire
. Avec Georges, on s offre le plaisir... sans la grosse fessee qui risquerait de recompenser ce genre d exploit dans la vraie vie. Dans le livre, on a le droit de tout faire et surtout, la magie existe. Elle cree la barriere entre le monde reel et celui du conte, aucune confusion n est possible. Rassurant pour les parents ! Et les dessins du grand illustrateur Quentin Blake sont simplement hilarants. --Pascale Wester. La plupart des grands-meres sont d adorables vieilles dames, gentilles et serviables. Helas, ce n est pas le cas de la grand-mere de Georges ! Grincheuse, ego?ste, elle ressemble a une sorciere et elle a des go?ts bizarres : elle aime se regaler de limaces, de chenilles .', '1', '128', 'papier/numerique', '2008');
INSERT INTO book VALUES('21', 'Sacres Sorcieres', 'Roald Dahld', '1983', 'Jeunesse', 'Ah! Si les sorcieres portaient vraiment de grandes robes noires, des chapeaux pointus, une verrue sur le nez et qu elles se promenaient sur des balais magiques, les choses seraient tellement plus simples ! La realite est beaucoup moins folklorique et beaucoup plus inquietante, Roald Dahl nous l apprend : les sorcieres sont pratiquement impossibles a identifier dans une foule.
Seuls de petits signes peuvent les trahir et il vaut mieux les connaitre, car les sorcieres n ont qu un but: eliminer les enfants qu elles detestent !
Lorsque notre jeune heros se retrouve bien malgre lui cache dans une piece ou les sorcieres tiennent leur congres annuel, les choses risquent de mal tourner...
On s amuse vraiment beaucoup a suivre les tribulations de ce petit garcon et de sa grand-mere, bien decides a lutter contre ces vilaines femmes qui ne revent que de transformer tous les enfants en souris. ', '1', '240', 'papier/numerique', '2008');
INSERT INTO book VALUES('22', 'Matilda', 'Roald Dahld', '1988', 'Jeunesse', 'Matilda raconte l histoire de Matilda Verdebois (Matilda Wormwood), une fillette particulierement eveillee vivant avec ses parents et son frere. Douee de grandes capacites intellectuelles, Matilda apprend seule a lire et ecrire, si bien qu a 5 ans, elle connait la plupart des grands classiques de la litterature britannique. Paradoxalement, elle n est l objet que de sarcasmes pour ses deux ignobles parents: l un est un escroc vendant des voitures volees, l autre ne jure que par le loto et les feuilletons televises. Le debut du roman retrace la vie de Matilda chez elle, jusqu au moment ou elle entre enfin a l ecole primaire. Des ses premiers jours a l ecole, son institutrice, Mlle Candy (Miss Honey), remarque son talent, aussi bien en lecture qu en mathematiques, et demande a ce qu elle passe dans une classe superieure. Mais la directrice, la redoutable Mlle Legourdin (Miss Trunchbull), refuse, pretextant que Matilda serait en realite une abominable manipulatrice, suivant les propos du pere de la jeune fille. Refusant de laisser cette situation telle quelle, mais impuissante face a cette megere, Mlle Candy fait alors en sorte que Matilda puisse reellement travailler, sans pour autant delaisser le reste des enfants, qui vouent un veritable culte a l institutrice.', '1', '253', 'papier/numerique', '2008');
INSERT INTO book VALUES('23', 'Charlie et la chocolatrie', 'Roald Dahld', '1964', 'Jeunesse', 'Charlie est un petit garcon qui vit avec son papa et sa maman, mais aussi avec ses quatre grands-parents. Tout ce monde est entasse dans deux pieces seulement car la famille de Charlie est tres pauvre. Lorsque son papa perd son travail, la situation devient dramatique, ils meurent presque de faim.
Mais dans la ville ou ils demeurent, il y a une mysterieuse chocolaterie : nul n y entre ni n en sort jamais. Son proprietaire, Mr Wonka, lance un grand concours : les cinq gagnants pourront visiter l usine et gagner des sucreries pour toute leur vie.
Mais les enfants mal eleves doivent se mefier : ils seront punis par ou ils auront peche. C est a une merveilleuse exploration que nous convie Roald Dahl, a l interieur d une usine fabuleuse qui recele absolument tout ce dont n importe quel gourmand peut rever et aussi d autres choses qu il n aurait pas ose imaginer : des machines qui fabriquent des bonbons inusables ou des chewing-gums-repas, des cascades de chocolat, des caramels qui font pousser les cheveux... ', '1', '224', 'papier/numerique', '2008');
INSERT INTO book VALUES('24', 'Les Miserables', 'Victor Hugo', '1862', 'Existentialisme', 'Je m appelle Jean Valjean. Je suis un galerien. J ai passe dix-neuf ans au bagne. Je suis libere depuis quatre jours et en route pour Pontarlier qui est ma destination. Quatre jours que je marche depuis Toulon.
Aujourd hui j ai fait douze lieues a pied. Ce soir en arrivant dans ce pays, j ai ete dans une auberge, on m a renvoye a cause de mon passeport jaune que j avais montre a la mairie. J ai ete a une autre auberge. On m a dit: - Va-t en! Chez l un, chez l autre. Personne n a voulu de moi.
J ai ete a la prison, le guichetier ne m a pas ouvert. J ai ete dans la niche d un chien. Ce chien m a mordu et m a chasse, comme s il avait ete un homme. On aurait dit qu il savait qui j etais. je m en suis alle dans les champs pour coucher a la belle etoile. Il n y avait pas d etoiles.
J ai pense qu il pleuvrait, et qu il n y avait pas de bon Dieu pour empecher de pleuvoir, et je suis rentre dans la ville pour y trouver le renfoncement d une porte.
La, dans la place, j allais me coucher sur une pierre, une bonne femme m a montre votre maison et m a dit: - Frappe la.
J ai frappe. Qu est-ce que c est ici? etes-vous une auberge? J ai de l argent, ma masse. Cent neuf francs quinze sous que j ai gagnes au bagne par mon travail en dix-neuf ans. Je paierai. Je suis tres fatigue, j ai bien faim. Voulez-vous que je reste?
- Madame Magloire, dit l eveque, vous mettrez un couvert de plus.', '1', '318', 'papier', '2008');
INSERT INTO book VALUES('25', 'Balzac et la Petite Tailleuse chinoise', 'Dai Sijie', '2000', 'Existentialisme', 'Dans la Chine de Mao, savoir lire, c est deja faire partie des intellectuels. Et on ne badine pas avec les intellectuels : on les envoie se reeduquer dans les campagnes, travailler dans des rizieres ou dans des mines. C est ce qui est arrive au narrateur et a son ami Luo, si jeunes et deja marques du sceau infamant d ennemis du peuple. Pour ne pas sombrer, ils ont heureusement encore quelques histoires, quelques films a se raconter, mais cela fait bien peu. Jusqu a ce que, par miracle, ils tombent sur un roman de Balzac : petit livre a lire en cachette, tellement dangereux, mais tellement magique, qui changera le cours de leur vie en leur ouvrant la porte de la fille du tailleur, en rendant possible ce qui ne l aurait jamais ete... Il fallait oser confronter le monde de Balzac et la Chine de Mao : Dai Sijie, realisateur renomme qui vit en France, a reussi cet improbable pari et on lit avec enthousiasme et frenesie ce premier roman parfaitement maitrise. ', '1', '224', 'papier', '2009');
INSERT INTO book VALUES('26', 'L Oeuvre', 'Emile Zola', '1886', 'Existentialisme', 'Claude Lantier est le fils de Gervaise Macquart et d Auguste Lantier (voir L Assommoir, roman ou l on apprend qu il a ete amene a l age de huit ans a Plassans par un vieux monsieur seduit par la qualite de ses dessins). Il apparait aussi dans Le Ventre de Paris. Il est ici l ami d?enfance du romancier Sandoz, personnage dans lequel Zola a mis beaucoup de lui-meme. Avec Sandoz et d autres peintres ou sculpteurs, Claude combat pour imposer une nouvelle forme de peinture, bien eloignee des canons neo-classiques qui ont la faveur des expositions officielles. Si certains d?entre eux reussissent finalement a s imposer, Lantier va pour sa part d echec en echec, demeurant incompris du public et souvent de ses propres amis.', '1', '492', 'papier', '2009');
INSERT INTO book VALUES('27', 'Candide', 'Voltaire', '1759', 'Conte philosophique', 'On sait tout de Candide, sauf une chose : quel rapport l auteur avait-il avec ses personnages ? Les a-t-il imagines ou connus ? A-t-il partage certaines de leurs aventures ? Est-il cache dans un coin du roman pour les observer ? Ce regard que Voltaire pouvait porter de l interieur sur sa creation, c est justement celui qu au-dela des connaissances acquises, on a eu l audace de tenter de porter sur Candide. Cette edition change l interpretation du plus etudie, mais aussi du plus secret des contes voltairiens. Il s y presente de facon nouvelle. Ce n est plus seulement, comme on l a dit, un catalogue de tous les malheurs humains, mis au service d une campagne philosophique contre la doctrine de la providence. C est, dans sa genese et dans sa structure, un voyage sentimental au pays de la memoire.', '1', '199', 'papier', '2010');
INSERT INTO book VALUES('28', 'Le Chevalier au bouclier vert', 'Odile Weulersse', '1990', 'Jeunesse', 'La pierre magique de Thibault a ete volee et apposee sur le front de la jeune fille qu il aime. Or ceci peut la tuer. Thibault n a que peu de temps pour retrouver la fee Hadelize, qui, seule, peut la sauver. Mais de terribles epreuves attendent Thibault... ', '1', '288', 'papier', '2006');
INSERT INTO book VALUES('29', 'Virus L I V 3', 'Christian Grenier', '2001', 'Jeunesse', 'Le gouvernement des Lettres a interdit les ecrans et decrete la lecture obligatoire. Face a cette tyrannie, les Zappeurs se revoltent : ces jeunes rebelles, adeptes de l image, propagent un virus qui efface les mots a mesure qu ils sont lus. Seule Allis est capable d identifier l inventeur du virus et de trouver un antidote. ', '1', '192', 'papier', '2006');
INSERT INTO book VALUES('32', 'Joyland', 'Stephen King', '2013', 'Policier', 'Les clowns vous ont toujours fait un peu peur?
L atmosphere des fetes foraines vous angoisse?
Alors, un petit conseil: ne vous aventurez pas sur une grande roue un soir d orage.

Apres une rupture sentimentale, Devin Jones, 21 ans, debarque l ete 1973 a Joyland, petit parc d attraction sur le littoral de la Caroline du Nord. Il est embauche avec d autres etudiants pour completer l equipe de forains, a la fois etrange et joyeuse. Sa rencontre avec un petit garcon doue de voyance, atteint d une maladie grave, et surtout de sa mere, va changer la vie de Devin. Obsede par le mystere du train fantome soi-disant hante par le spectre d une femme egorgee 4 ans auparavant, le jeune homme se lance dans l enquete. Un nouveau meurtre est-il possible? Parviendra-t-il a l eviter? Une chose est sure, l aventure le changera a jamais.', '1', '400', 'papier/numerique', '2016');
INSERT INTO book VALUES('31', 'L Art et la maniere', 'Danielle Guisiano', '2015', 'Romance', 'Entre sa carriere d infirmier et sa petite amie Severine, Julien avait planifie son avenir. Jusqu au jour ou Severine le quitte, pretextant qu il ne sait pas faire l amour. D abord vexe et destabilise, Julien se ressaisit et s inscrit au Bleuet, un institut de coaching specialise dans l art et la maniere de developper sa sensualite. Allonge seul dans une cabine qui le coupe du monde, guide par une voix anonyme, il va apprendre a lacher prise, prendre peu a peu confiance en ses emotions et ses sensations. Mais une fois sorti du cocon du Bleuet, Julien retrouve toutes ses difficultes. ? l hopital, il est incapable de garder la distance affective qui le separe d un jeune patient et de sa maman, Amandine. Quoiqu il fasse, il ne parvient pas a les laisser s effacer de sa vie. Ou qu il aille, cette mysterieuse jeune femme se trouve sur son chemin. Pur hasard ou curieuse co?ncidence ?', '1', '133', 'numerique', '2016');
INSERT INTO book VALUES('35', 'Harry Potter et la Coupe de feu T4', 'J K Rowling', '2000', 'Fantastique', ' Age de quatorze ans, Harry est tourmente par des cauchemars dans lesquels il rentre en connexion avec l esprit de Voldemort, voyant ainsi tout ce que fait celui-ci. En vacances chez les Weasley, il assiste a la coupe du monde de Quidditch, durant laquelle les fideles de Voldemort (les Mangemorts) defilent en semant la terreur et la panique dans le campement ou Harry et les Weasley se trouvent. La marque des tenebres apparait lancee par un inconnu. Les trois amis retournent a Poudlard pour la rentree des classes, ou il apprennent que cette annee a Poudlard est marquee par le retour du ? Tournoi des Trois Sorciers ?, ancien tournoi qui opposait regulierement un apprenti sorcier de chaque ecole de sorcellerie les plus prestigieuses d Europe, autrement dit Poudlard, Beauxbatons et Durmstrang.', '1', '652', 'papier/numerique', '2010');
INSERT INTO book VALUES('33', 'Harry Potter et la chambre des secrets T2', 'J K Rowling', '1998', 'Fantastique', ' Harry Potter passe l ete chez les Dursley et recoit la visite de Dobby, un elfe de maison. Celui-ci vient l avertir que des evenements etranges vont bientot se produire a Poudlard et lui conseille donc vivement de ne pas y retourner. Harry choisit d ignorer cet avertissement. Le jour de son depart pour l ecole, il se retrouve bloque avec Ron Weasley a la gare de King s Cross, sans pouvoir se rendre sur le quai 9 ? ou les attend le Poudlard Express. En dernier recours, les garcons se rendent donc a Poudlard a l aide de la voiture volante de Monsieur Weasley et manquent de peu de se faire renvoyer des leur arrivee a l ecole pour avoir ete apercus au cours de leur voyage par plusieurs moldus. Le nouveau professeur de defense contre les forces du mal, Gilderoy Lockhart, se montre particulierement narcissique et inefficace.', '1', '275', 'papier/numerique', '2009');
INSERT INTO book VALUES('34', 'Harry Potter et le Prisonnier d Azkaban T3', 'J K Rowling', '1999', 'Fantastique', ' Durant l ete, pour son treizieme anniversaire, Harry recoit plusieurs cartes de ses amis, notamment une lettre de Ron qui lui ecrit d egypte, ou il passe ses vacances avec sa famille. Une lettre du professeur McGonagall, directrice adjointe de Poudlard, lui informe que les eleves de troisieme annee auront la possibilite de visiter le village de Pre-au-Lard. Le lendemain, les informations televisees moldues annoncent l evasion d un tres dangereux prisonnier du nom de Sirius Black et l oncle et la tante de Harry s inquietent legerement pour eux-memes. Plus tard, ils annoncent a Harry que la tante Marge sejournera une semaine chez eux, a Privet Drive. La tante Marge provoque Harry en traitant son pere defunt d ancien ivrogne. Harry s enerve, perd le controle de sa magie et fait accidentellement gonfler la tante Marge comme un ballon. Alors que son oncle, furieux, ordonne a Harry de rendre a Marge son apparence normale, le garcon refuse et prend la fuite en pleine nuit, emportant sa valise et sa chouette Edwige.', '1', '349', 'papier/numerique', '2009');
INSERT INTO book VALUES('39', 'L Aine T2', 'Christopher Paolini', '2006', 'Fantasy', ' Eragon et Saphira, sa dragonne, sont a peine sortis vainqueurs de la bataille de Farthen D?r que des urgals attaquent de nouveau et tuent le chef des Vardens...
Nasuada, sa fille, est nommee a leur tete. Apres lui avoir prete allegeance, Eragon entreprend avec Saphira un long et perilleux voyage vers Ellesmera, le royaume des elfes, ou ils recevront les enseignements du fameux Togira Ikonoka, l infirme Inchange.
Pendant ce temps, Roran, le cousin d Eragon, organise la defense de son village contre les Ra zcs. Le jeune homme est persuade qu ils veulent recuperer la mysterieuse pierre trouvee par Eragon sur la Crete. De son cote le royaume de Surda est toujours en lutte contre Galbatorix.
Eragon, Roran, Les Vardens et les rebelles du Surda poursuivent desormais un seul et meme but: detruire les forces du mal.
', '1', '804', 'papier/numerique', '2014');
INSERT INTO book VALUES('40', 'Brisingr T3', 'Christopher Paolini', '2009', 'Fantasy', ' Eragon a une double promesse a tenir : aider Roran a delivrer sa fiancee, Katrina, des griffes des Ra zacs, et venger la mort de son oncle Garrow. Mais le combat continue contre Galbatorix. Les nains, les elfes, le peuple du Surda et les Urgals eux-memes se rallient aux Vardens, sous l autorite de Nasuada. Ce qui ne va pas sans frictions et rivalites. Quant a Eragon et Saphira, ils n ont pas acheve leur formation. L enseignement et les conseils d Oromis et de Glaedr, le dragon d or, leur sont plus que jamais necessaires, car, entre batailles contre les soldats du tyran, luttes intestines et souffrances secretes - l elfe Arya est toujours presente dans les pensees d Eragon -, le jeune Dragonnier et sa puissante compagne aux ecailles bleues doivent sans cesse donner le meilleur d eux-memes. Or, depuis que Murtagh lui a repris Zar roc, Eragon n a plus d epee...
', '1', '825', 'papier/numerique', '2014');
INSERT INTO book VALUES('56', 'Piege de Neige', 'Lisa Jackson', '2010', 'Policier', ' Prisonniere d un cachot obscur, transie de froid, l inspecteur Regan Pescoli essaie coute que coute de garder son sang-froid en depit de sa terreur grandissante. Car elle ne connait que trop la cruaute de l homme qui a reussi a l attirer dans ce piege mortel. Un homme qu elle traque depuis des semaines dans l hiver glacial du Montana, un veritable pervers qui reserve un sort atroce a ses victimes. Desormais, elle le sent, seul son instinct pourra lui eviter le pire. Son instinct, mais aussi l amour qu elle eprouve pour ses enfants et pour Nate Santana, l homme qui a finalement su gagner son coeur. Resolue a tenter l impossible, elle decide d ignorer la peur et d utiliser tout ce qu elle sait du tueur pour essayer de transformer la relation a son avantage. Mais comment parvenir a dominer psychologiquement son ravisseur, et trouver la faille qui lui permettra de s echapper ?', '1', '464', 'numerique', '2016');
INSERT INTO book VALUES('42', 'Donjon de Naheulbeuk La couette de l oubli T2', 'John Lang', '2008', 'Heroic-Fantasy / Humour', ' La Couette de l oubli reprend la ou s etait arrete le dernier episode de la saison 2. ? peine remis de leurs aventures qui leur ont rapporte un salaire miserable (166 pieces d or et 6 pieces d argent chacun), les aventuriers les plus pathetiques de la terre de Fangh sont pourtant dans une panade encore plus noire. Ils ont donne sans le savoir a Gontran Theogal la derniere statuette qui lui permettra d accomplir la prophetie reveillant Dlul et plongeant le monde dans un sommeil eternel. Par chance pour eux, l avant-derniere statuette a ete volee et, sous la menace de Tulgar, ils vont devoir tout faire pour retrouver cette autre statuette et sauver le monde.', '1', '376', 'papier', '2016');
INSERT INTO book VALUES('43', 'Donjon de Naheulbuk L Orbe de Xaraz T3', 'John Lang', '2009', 'Heroic-Fantasy / Humour', ' L Orbe de Xaraz reprend quelques jours apres la fin de La Couette de l Oubli, ou les heros, bien qu ils viennent de sauver le monde du retour de Dlul, sont toujours aussi pauvres et demoralises. Apres une course-poursuite avec un geant des collines, leurs mesaventures les enjoignent encore a fuir, jusqu au moment ou l un des leurs meurt accidentellement. N ayant aucun point de destin, il n est possible de le ramener a la vie que par un puissant sortilege. La dissolution de la Compagnie est donc remise a plus tard... La compagnie des Fiers de Hache est utilisee pour un complot : les comploteurs les envoient sur une mission bidon qui a lieu pendant un match de brute balle (sport de balle fictif) qui attire de nombreux supporters. Les comploteurs emploient volontairement une equipe lamentable pour qu elle se fasse prendre et declencher un conflit conforme a leur souhait. Malheureusement pour les comploteurs, la compagnie des Fiers de Hache n entre pas dans le bon donjon.
? la fin du roman, il s avere que l equipe a de nouveau sauve le monde (involontairement, evidemment).
', '1', '380', 'papier', '2016');
INSERT INTO book VALUES('44', 'Donjon de Naheulbeuk le Conseil de Suak T4', 'John Lang', '2011', 'Heroic-Fantasy / Humour', ' Les peuples de la Terre de Fangh s agitent alors qu une serie d agressions touche les differents peuples sans que le responsable soit identifie : en effet, des Barbares attaquent la Caisse des Donjons, des Elfes sylvains tuent la garde de nuit de Glargh, et des Nains vandalisent un village de Hobbits.
Chacun dementant vigoureusement les faits qui lui sont reproches, le concile de Waldorg decide d organiser une reunion permettant de mettre au clair l affaire, a la tour de Suak. La compagnie dont on suit les aventures depuis le debut se retrouve en plein c?ur du conflit depuis que l Elfe est devenue la reine des Sylvains de Folonariel, a son grand malheur ; elle tentait de se faire oublier depuis l incident du stade de Glargh. Desormais connue sous le nom de Selenia III, l Elfe s installe avec le reste de la Compagnie dans le bois N talamela, et doit trouver un moyen d inculquer l art du combat a un peuple pacifique : le Barbare, auto-proclame chef Taurogh, initie les sylvains a la force de ses poings, le Ranger profite de son nouveau grade de ? clipitaine de l armee ? et de l affectuosite des elfettes, la Magicienne se desespere des lacunes en magie, et le Nain et l Ogre pleurent leurs conditions de vie, dans la nature et au regime vegetarien. Une fois installe a leur poste, la Compagnie reprend la route avec deux conseillers elfes, Naziel et Nuliel, pour la tour de Suak, lieu ou se tiendra le conseil exceptionnel reunissant l ensemble des peuples de la Terre de Fangh. ', '1', '380', 'papier', '2016');
INSERT INTO book VALUES('45', 'Donjon de Naheulbeuk Chaos sous la montagne T5', 'John Lang', '2014', 'Heroic-Fantasy / Humour', ' C est la guerre entre les forces alliees de Fangh (humains, sorciers, elfes et aventuriers) et les troupes de Gzor (orques, gobelins et mages noirs). Apres une violente bataille, l etat-major des forces alliees se rend compte qu il sera difficile de vaincre les troupes du chaos et decide d utiliser d autres methodes que le combat. L etat-major engage Les \"Fiers de Hache\" (le ranger, la magicienne, l elfe, le nain, le barbare, l ogre et une pretresse recrutee depuis peu, Sonjaska) pour sauver le monde encore une fois. L etat-major leur revele l existence d une cite abandonnee depuis des siecles dans le desert : Rancurac. Autrefois des mages s installerent dans cette cite pour faire des recherches et y creer des sorts. Au bout de quelques annees, a la suite de divers incidents, les mages durent evacuer la cite et scellerent l entree sans avoir pu emporter leur parchemins ou etaient inscrits les sortileges qu ils avaient invente. La cle pour entrer dans la cite fut confiee aux nains de Mir-Nodd. Aujourd?hui (des siecles plus tard), l etat-major charge Les \"Fiers de Hache\" d aller recuperer la cle chez les nains puis de partir a la recherche de cette cite perdue du desert', '1', '380', 'papier', '2016');
INSERT INTO book VALUES('46', 'L Epee de Verite La Pierre de larmes T2', 'Terry GoodKing', '2003', 'Fantasy', ' Richard, Zedd et Kahlan croyaient en avoir fini avec les tenebres. Mais leur victoire sur le tyran Darken Rahl a des consequences terribles qu ils ne pouvaient l imaginer. Le voile qui separe le monde des vivants et le royaume des morts s est dechire. Le Gardien des enfers sera bientot en mesure de le traverser... Il a deja reveille ses serviteurs. Leurs manigances sement le feu et le sang. Desormais, le danger est partout, il rode et nul ne peut lui echapper. Pour Zedd le sorcier, l unique espoir reside en une certaine pierre, la petite fille qui la porte... et le Sourcier de Verite. Richard est face a son destin. Car, s il refuse d etre un magicien, il n en subit pas moins les atroces souffrances liees a ce don. S il n apprend pas la magie, il mourra. Les Soeurs de la Lumiere la lui enseigneront, a condition qu il se soumette. Or pour rien au monde Richard ne veut revivre le cauchemar d etre esclave. Mais s il renie son heritage, il condamne l avenir du monde. Une seule personne detient le pouvoir de faire accepter a Richard ce qu il abhorre : Kahlan, la Mere Inquisitrice', '1', '700', 'papier/numerique', '2015');
INSERT INTO book VALUES('47', 'L Epee de Verite Le sang de la dechirure T3', 'Terry GoodKing', '2004', 'Fantasy', ' La barriere qui separait l Ancien et le Nouveau Monde a ete brisee. Des forces anciennes viennent assieger les Contrees du Milieu. Des forces si terrifiantes que, la derniere fois qu elles ont frappe, il y a 3000 ans, on n a pu les repousser qu en murant l Ancien Monde a l aide d une barriere magique infranchissable. A present celle-ci n est plus, et Richard Rahl et Kahlan Amnell sont les seuls a pouvoir faire face aux puissances malefiques qui vont deferler. Richard est le Sourcier de Verite, mais il est aussi un sorcier de guerre, le premier depuis des millenaires. Quant a Kahlan, sa bien-aimee, elle se cache loin de lui, traquee par des fanatiques qui ont entrepris d assassiner tous les possesseurs de magie. Ils se font appeler le Sang de la Dechirure, ils torturent et tuent des innocents en pretendant lutter contre le Mal. Alors que regnent la manipulation et la guerre, Richard devra tout faire pour empecher une apocalypse d une sauvagerie inimaginable : accepter le pouvoir qu il a herite de son pere et utiliser toutes ses ressources magiques pour vaincre l ennemi, sauver Kahlan et refermer le portail.', '1', '536', 'papier/numerique', '2015');
INSERT INTO book VALUES('48', 'La Malediction de l epouvanteur T2', 'Delaney Joseph', '2006', 'Fantasy', ' Le Fleau est une des plus dangereuses creatures qui existe. Enferme sous la cathedrale de Priestown, il gagne de plus en plus de puissance et s introduit dans l esprit des plus faibles. ?a ne peut plus durer, il faut le detruire une bonne fois pour toutes. Mais la tache s avere perilleuse : le maitre de Thomas, apprenti ?pouvanteur, a deja echoue contre cette creature autrefois, et en garde un bien mauvais souvenir.
Les choses se compliquent encore lorsque l Inquisiteur Witchfinder arrive en ville. Cet homme mene une chasse aux sorcieres et a tout ce qui s approche de l \"obscur\". Il reve donc de capturer l ?pouvanteur pour le mettre sur le B?cher. Il faudra faire tres attention...
', '1', '361', 'numerique', '2016');
INSERT INTO book VALUES('50', 'Percy Jackson et la mer des monstres T2', 'Rick Riordan', '2006', 'Fantasy', ' Percy a passe une nouvelle annee dans un nouveau college d ou, par miracle, il a reussi a ne pas se faire expulser. Il s est lie d amitie avec Tyson, un grand gaillard tres timide, et le defend contre toutes les brutes qui se moquent de lui. Alors que ses nuits sont peuplees de cauchemars concernant son meilleur ami le satyre Grover, une partie de balle aux prisonniers se transforme en veritable carnage a cause de nouveaux arrivants tres particuliers. Annabeth Chase vient chercher Percy pour rentrer a la colonie des Sang-Mele, et c est ainsi qu il apprend que l arbre de Thalia, defunte fille de Zeus, dieu du ciel et roi du pantheon grec, se meurt pour une raison inconnue. Avec Chiron expulse, Monsieur D. tres peu autoritaire par rapport a Tantale, son nouveau collegue sorti des Enfers pour s occuper des jeunes demi-dieux, Percy pense que la colonie est vouee a sa perte. Tandis que les barrieres magiques s epuisent, Tyson s avere etre une creature a qui les gens n osent pas faire confiance.
Clarisse, fille de l arrogant Ares, partira pour une quete dans l espoir de trouver la Toison d Or et soigner l arbre mourant de Thalia. Mais Percy, Annabeth et Tyson la suivront avec l aide d Hermes, le pere de Luke, et devront deployer beaucoup d efforts afin de retrouver la fameuse Toison detenue par le cyclope Polypheme et delivrer Grover, qui etait en fait prisonnier dans sa grotte, attire par la magie de la Toison.
De retour a la colonie, la Toison avec eux, l arbre guerit, rejetant le poison qui le tuait. Mais l antidote aura aussi un effet imprevu qui changera plus que tout le cours des evenements.
', '1', '352', 'papier/numerique', '2014');
INSERT INTO book VALUES('51', 'Percy Jackson et le sort du titan T3', 'Rick Riordan', '2007', 'Fantasy', ' Annabeth Chase, Percy Jackson et Thalia Grace partent un jour de decembre chercher deux demi-dieux dans une ecole militaire. Pendant le sauvetage, Annabeth se fait enlever par le proviseur, qui se revele etre une manticore. Sauves par les Chasseresses d Artemis (deesse de la chasse) et par Artemis elle-meme, ils expliquent a leurs deux nouveaux compagnons, Bianca et son frere Nico di Angelo, leur condition de demi-dieux. Bianca rejoint les Chasseresses.
Au matin, Artemis part seule chasser un des monstres les plus dangereux (qui se revelera etre l Ophiautoros, sauve par Percy). Tout le groupe est conduit par Apollon vers la colonie des Sang-Mele.
Artemis est a son tour enlevee. Une quete unissant demi-dieux et Chasseresses est alors lancee pour retrouver la deesse et sauver Annabeth. Le monde entier en depend.
', '1', '327', 'papier/numerique', '2014');
INSERT INTO book VALUES('52', 'Percy Jackson et Lla bataille du labyrinthe T4', 'Rick Riordan', '2008', 'Fantasy', ' Apres avoir, lors des portes ouvertes, incendie la nouvelle ecole qui etait censee l accueillir, Percy se retrouve une nouvelle fois a la Colonie des Sang-Meles avec Annabeth.
Grover, de son cote, apres ses echecs dans la quete de Pan se voit accorder un delai d une semaine supplementaire par le Conseil des Sabots Fendus.
Sachant pertinemment que Luke cherche a combattre la Colonie en y entrant par le Labyrinthe du celebre Dedale, lorsque Percy et Annabeth finissent par tomber dans une entree du Labyrinthe menant droit a la Colonie, une quete est lancee, avec Annabeth, Percy, Grover et Tyson. Leur but est multiple : trouver Dedale et l empecher d aider Luke, et pour Grover, retrouver Pan. Commence alors une aventure dans l obscurite du Labyrinthe, pleine de monstres divers et varies, de rencontres impromptues, d epreuves et de pieges, au cours de laquelle ils retrouveront Nico di Angelo le fils d Hades et le persuaderont de repasser de leur cote. Le groupe se separera au detour d un chemin dont Grover est s?r qu il le menera vers Pan. Hepha?stos revele a Percy le moyen le plus s?r de se diriger dans le Labyrinthe : la vue claire d un mortel a travers la Brume. La solution qui s offre a eux est Rachel Elizabeth Dare.', '1', '410', 'papier/numerique', '2014');
INSERT INTO book VALUES('53', 'Percy Jackson et le dernier olympien T5', 'Rick Riordan', '2010', 'Fantasy', ' La fin du monde a commence. Lorsque Charles Beckendorf atterrit sur la Prius de Paul avec Blackjack le Pegase, Percy sait que c est fini.
Leur mission consiste a faire exploser le Princesse Andromede. La mission est reussie, mais au prix de la mort de Beckendorf, lui et Percy ayant ete denonces par un espion interne a la Colonie. De retour a la Colonie, Percy est mis au courant de la Prophetie complete. Il y trouve Nico di Angelo, qui le convainc de se plonger dans le Styx pour recevoir l invincibilite. La guerre commence. ? Manhattan, les mortels sont endormis par Morphee, qui est passe du cote de Cronos. la bataille oppose la Colonie aux forces des Titans. Typhon, qui s est reveille marche droit vers New York, a peine ralenti par les dieux. Durant la bataille, Percy se retrouve a affronter une truie geante, des divinites fluviales, le Titan Hyperion, et meme un drakon. Poseidon, convaincu par Percy, se joint au combat et terrasse Typhon. Hades, jusque-la reste dans son royaume se joint egalement a la bataille. Cronos finit par acceder a la salle du trone de l Olympe. Le combat final va s y derouler.', '1', '425', 'papier/numerique', '2016');
INSERT INTO book VALUES('54', 'Le Linceul de glace', 'Lisa Jackson', '2014', 'Policier', ' La periode des fetes ? Un calvaire pour Selena Alvarez. Cette annee encore, elle va devoir supporter l ambiance festive et familiale qui regnera pendant plusieurs semaines a Grizzly Falls, petite ville du Montana ensevelie sous la neige. Et par-dessus tout, elle devra faire face a sa solitude, une solitude qui la renvoie a un passe auquel elle s efforce habituellement de ne pas penser.
Mais un meurtre, particulierement atroce, va l obliger a se concentrer sur son travail, et a tenir a l ecart ses propres fantomes. Le cadavre d une femme nue, enchasse dans la glace et comme sculpte par les mains du tueur, est en effet retrouve dans la creche de l eglise presbyterienne de Grizzly Falls. Une mise en scene scabreuse, terrifiante, que Selena doit decrypter a tout prix si elle veut arreter le meurtrier. Pour cela, elle aura besoin de l aide de sa coequipiere, Regan Pescoli, et du troublant detective Dylan O Keefe. Avec eux, elle va plonger dans une enquete qui l obligera, qu elle le veuille ou non, a faire face a ses plus noirs souvenirs.', '1', '440', 'papier', '2016');
INSERT INTO book VALUES('55', 'L Hiver Assassin', 'Lisa Jackson', '2010', 'Policier', ' Ne meurs pas. Bats-toi. Ne te laisse pas affaiblir par le froid et la morsure du vent. Oublie la corde et l ecorce gelee. Bats-toi.
C est la quatrieme femme morte de froid que l on retrouve attachee a un arbre dans le Montana, un etrange symbole grave au-dessus de la tete. Horrifiees par cette serie macabre, Selena Alvarez et Regan Pescoli, inspecteurs de police, se lancent dans une enquete qui a tout d un cauchemar, au coeur d un hiver glacial et de jour en jour plus meurtrier a Grizzly Falls.Au meme moment, Jillian Rivers, partie a la recherche de son mari dans le Montana, se retrouve prisonniere d une violente tempete de neige. Un homme surgit alors pour la secourir avant de la conduire dans une cabane isolee par le blizzard. Malgre son soulagement, Jillian eprouve instinctivement pour cet etre taciturne un sentiment de mefiance. Et si ses intentions n etaient pas aussi bienveillantes qu il y paraissait ? Car, pour Selena, Regan et Jillian, un hiver assassin se profile peu a peu dans ces forets inhospitalieres', '1', '576', 'papier/numerique', '2016');
INSERT INTO book VALUES('57', 'Vie d Immortelle, tourments eternels', 'Aurelie Poure', '2013', 'Fantasy Romance', ' Quand Madeline-Rose, vampire depuis plusieurs decennies, rencontre l humain Jonathan, la passion les consume. Lui cachant d abord son secret, les doutes la rongent a l idee qu elle soit contrainte a quitter l homme qu elle aime. Mais ni la soif de sang qui la devore, ni son lourd passe ne parviennent a les separer.
L Obsession melee aux sentiments va faire basculer les choses, et leur amour interdit va dechainer des evenements plus forts qu eux.', '1', '342', 'numerique', '2016');
INSERT INTO book VALUES('58', 'La sirene', 'Kiera Cass', '2016', 'Fantasy Romance', ' Kahlen est une Sirene, vouee a servir son maitre l Ocean en poussant les humains a la noyade. Son arme ? Une voix fatale pour qui a le malheur de l entendre... et qui l oblige a se faire passer pour muette lorsqu elle sejourne sur la terre ferme.
Akinli, lui, est un seduisant jeune homme, qui incarne tout ce dont Kahlen a toujours reve.
Alors que leur amour naissant leur fait courir un grave danger, Kahlen est-elle prete a tout risquer pour Akinli ?', '1', '360', 'numerique', '2016');
INSERT INTO book VALUES('59', 'Succubus Blue', 'Richelle Mead', '2009', 'Fantasy Romance', ' Georgina Kincaid est succube. A priori un choix de carriere plutot sympa : la jeunesse eternelle, l apparence de son choix et des hommes prets a tout pour un simple effleurement. Pourtant, sa vie n est pas si glamour : pas moyen de decrocher un rencard sans mettre en peril l ame de l heureux elu. Heureusement son travail en librairie la passionne. Mais pour l heure, Georgina est propulsee au coeur de la tourmente, et ses sortileges sexy et sa langue bien pendue ne lui seront d aucun secours. ', '1', '512', 'numerique', '2016');
INSERT INTO book VALUES('60', 'Superbia', 'Frederique De Keyser', '2016', 'Fantasy Romance', ' Jeune nymphe orgueilleuse, Aphea a autrefois cause le suicide d un pretendant qu elle a cruellement econduit. Reniee par les siens, condamnee par les dieux a d eternelles peines amoureuses, elle mene desormais une vie solitaire. Un jour, elle assomme un guerrier wisigoth qui tente de l approcher. Prise de remords, la nymphe recueille ce bel inconnu, qu elle decide de guerir. Mais bientot, en proie a un puissant desir l un pour l autre, ils cedent a la passion qui les devore. Pourtant, les dieux les epient.', '1', '160', 'numerique', '2016');
INSERT INTO book VALUES('61', 'La Panthere de l amour', 'Frederique De Keyser', '2016', 'Fantasy Romance', ' Ame solitaire, Darina s est resignee a mener une triste vie. Jusqu au jour ou elle fait la rencontre du shaman Saran qui la sauve des griffes de son agresseur. S ils eprouvent l un pour l autre un puissant desir, Saran semble toutefois prendre certaines distances, a tel point qu il disparait. Or, incapable d oublier son sauveur, Darina entreprend un periple pour le rejoindre sur les rives du Lac Baikal. Si Saran est heureux de la revoir, il lui parait pourtant trouble. Quels secrets dissimule-t-il ? Et quelle est donc cette force animale qui prend parfois possession de lui ?', '1', '160', 'numerique', '2016');
INSERT INTO book VALUES('62', 'Harry Potter et Le Prince de Sang Mele T6', 'J K Rowling', '2005', 'Fantastique', ' Harry rentre en sixieme annee a l ecole de sorcellerie Poudlard. Il entre alors en possession d un livre de potion portant le mot propriete du Prince de sang-mele et commence a en savoir plus sur le sombre passe de Voldemort qui etait encore connu sous le nom de Tom Jedusor.', '1', '720', 'papier/numerique', '2016');
INSERT INTO book VALUES('63', 'Le Seigneurs des anneaux : La communaute de l anneau T1', 'JRR Tolkien', '1954', 'Fantasy', ' Tout commence avec les cent onze ans de Bilbo Sacquet, le heros de Bilbo le Hobbit, qui, fidele a sa reputation d excentricite, disparait au beau milieu de la prodigieuse fete donnee pour feter son anniversaire. Toutes ses possessions vont a son neveu Frodo, y compris le petit anneau d orâ€¦ petit anneau dont la nature est finalement elucidee par Gandalf : il s agit de l Anneau Unique, forge par Sauron, le Seigneur des Tenebres, pour dominer tous les autres. Frodo se voit contraint de quitter l apparente securite de la Comte pour partir en un perilleux voyage jusqu a Fondcombe et, au-dela, vers les Crevasses du Destin, Â« au pays de Mordor ou s etendent les ombres Â», pour detruire l Anneau et mettre un terme au pouvoir de Sauron. ', '1', '704', 'papier/numerique', '2016');
INSERT INTO book VALUES('64', 'Le Seigneurs des anneaux : Les deux tours T2', 'JRR Tolkien', '1954', 'Fantasy', ' La Communaute de l Anneau est divisee. Frodo poursuit sa quete en direction du Mordor, tandis que les autres se dirigent vers le Rohan. Ils y trouvent la guerre et tiennent desesperement le Gouffre de Helm face aux Orques de l Isengard. Pendant ce temps, Frodo traverse des paysages inhabites, desoles et dangeureux, jusqu a la Porte Noire. Mais l acces impossible l obligera a chercher un autre passage plus au sud. Il sera capture par les Rodeurs d Ithilien mene par Faramir, mais reprendra tout de meme la route a la rencontre d Arachne. ', '1', '546', 'papier/numerique', '2016');
INSERT INTO book VALUES('65', 'Le Seigneur des anneaux : Le Retour du Roi T3', 'JRR Tolkien', '1955', 'Fantasy', ' La Communaute se divise toujours plus : certains sont desormais a Minas Tirith, la capitale du Gondor, tandis que d autres sont encore en Rohan. Mais aux frontieres du Mordor, Sam decide de continuer la quete de destruction de l Anneau, il assume le lourd fardeau, avant de comprendre de la bouche des Orques, que Frodo n est pas mort. Avec courage, il libere Frodo et ils tenteront ainsi d achever la quete. Pendant ce temps, les troupes de Sauron quittent le Mordor en direction de Minas Tirith. La ville se prepare a l assaut et espere voir venir des renforts inesperes. Et enfin se terminera la Guerre de l Anneau. ', '1', '576', 'papier/numerique', '2016');
INSERT INTO book VALUES('67', 'De glace et de tenebres', 'Lisa Jackson', '2013', 'Policier', ' Selena Alvarez en est persuadee : l affaire sur laquelle elle et sa coequipiere Regan Pescoli enquetent est hors normes. D abord parce que les victimes toutes des femmes â€” se ressemblent etonnamment : ossature du visage, peau claire, cheveux auburn, yeux verts. Ensuite parce que le tueur, qui s attaque methodiquement et froidement a ses victimes, semble insaisissable et tout proche a la fois.
Comme si, cache dans l ombre, epiant ses victimes jusqu a s impregner de leurs moindres habitudes, il attendait son heure pour frapper, de nouveau.
En pleine periode de Thanksgiving, dans ce Montana de tenebres et de glace que les decorations de Noel peinent a rechauffer, Selena sait qu elle va devoir faire preuve d une ingeniosite et d un courage sans egal pour arreter ce tueur implacable. Et pour reveler au grand jour le terrible secret qui le pousse a agir.', '1', '576', 'papier/numerique', '2016');
INSERT INTO book VALUES('68', 'Dernier Soupir', 'Lisa Jackson', '2015', 'Policier', ' Selena Alvarez et Regan Pescoli le savent depuis longtemps : la realite se fait parfois plus noire que nos cauchemars les plus sombres. Par exemple lorsque le sherif Grayson, leur chef dans la police de Grizzly Falls, est victime d une tentative de meurtre et se retrouve entre la vie et la mort : un sniper a tente de l abattre alors qu il sortait de son chalet dans les hauteurs de la ville. Sous le choc, les deux inspectrices se demandent tres vite s il existe un lien entre cette tentative d assassinat et le meurtre recent de la juge Samuel-Picquard, dans les bois de Grizzly Falls. Et si les deux affaires sont liees, quelles peuvent bien etre les motivations de ce tueur froid, implacable qui, elles le pressentent, ne s arretera pas la ?
Dans cette enquete hors normes, Regan et Selena vont devoir controler leur emotion et leur colere. A ce prix seulement elles conserveront toute la lucidite necessaire pour capturer le tueur. Le capturer, avant qu il n arrache son dernier soupir a sa prochaine victime.', '1', '520', 'papier/numerique', '2016');
INSERT INTO book VALUES('69', 'Dans les brumes de Grizzly Falls', 'Lisa Jackson', '2016', 'Policier', ' Le cauchemar a commence dans la moiteur du bayou de Louisiane. Pour echapper au meurtrier qui la poursuit sans relache, Anne-Marie Calderone a fui La Nouvelle-Orleans et rejoint Grizzly Falls, en esperant sauver sa peau grace a l aide du sherif Dan Grayson, sa derniere chance.
Mais, ici aussi, le cauchemar la happe. Une jeune femme est retrouvee morte dans la riviere gelee, l annulaire de la main gauche sectionne. Le signe que le tueur sait ou se cache Anne-Marie', '1', '432', 'papier/numerique', '2017');
INSERT INTO book VALUES('70', 'La legende des loups, T1 L Empreinte du Loup', 'Rhyannon Byrd', '2010', 'Fantasy Romance', ' Torrance a l impression de vivre un cauchemar eveille. Mason, l homme Qui vient de la sauver des etres effrayants qui la traquent sans relache, est lui aussi un loup-garou, une des creatures Qui hantent ses nuits depuis toujours. Pourtant, afin d echapper a la terrifiante menace Qui pese sur elle, elle accepte de le suivre, fascinee malgre elle par la force et le magnetisme Qu il degage. Bientot, Mason lui revele qu elle est son \" ame soeur \" et que c est ce lien Qui a attire sur elle la vengeance des loups rebelles. Troublee par cet aveu, captivee par la beaute sauvage de l homme-loup, Torrance se laisse peu a peu seduire. Mais tandis Que son amour grandit, Mason semble se detourner d elle. Comme si le lien entre eux etait trop fort, comme s il craignait de la mettre en danger, en succombant a ses propres sentiments', '1', '280', 'numerique', '2017');
INSERT INTO book VALUES('71', 'La Legende des Loups T2 L Appel de la Nuit', 'Rhyannon Byrd', '2010', 'Fantasy Romance', ' Depuis dix ans, Jeremy Burns tente d oublier Jillian Murphy, la femme-loup du clan des Silvercrest, qui l a rejete parce qu il n etait qu un sang-mele, fils d un loup-garou et d une humaine. Des annees durant, il a multiplie les conquetes, essayant sans y parvenir de remplacer celle qu il considere toujours comme son ame soeur. Mais voila qu aujourd hui, une mission de la plus haute importance l oblige a revenir au sein du clan. Stupefait, il decouvre alors que Jillian est devenue la chamane des Silvercrest, une femme aux pouvoirs immenses. Malgre sa rancoeur, il se resout a lui demander son aide, meme s il sent deja qu il va avoir le plus grand mal a dominer cet incontrolable desir qui le met au supplice lorsqu il est aupres d elle', '1', '278', 'numerique', '2017');
INSERT INTO book VALUES('72', 'La Legende des Loups T3 Dans l Ombre du Loup', 'Rhyannon Byrd', '2010', 'Fantasy Romance', ' Parce qu une bande de loups enrages a designe Michaela comme leur prochaine victime, les membres du clan des Silvercrest ont charge Brody Carter de ramener la jeune humaine dans la foret et de la garder sous sa protection. Avec sa stature de geant et son visage barre de cicatrices, Brody Carter semble peu designe pour inspirer confiance. Pourtant, des le premier regard, Michaela, fascinee par cet etre sauvage au regard d ambre, accepte de le suivre et de s installer pour quelques jours dans sa demeure. Commence alors une etrange cohabitation entre la jeune humaine et son garde du corps. Tandis que Brody entoure sa protegee d une attention discrete, Michaela se demande comment abattre les defenses de l homme-loup dont l ame et le cÅ“ur semblent verrouilles. Comme si des blessures secretes l empechaient d aimer et d etre aime', '1', '280', 'numerique', '2017');
INSERT INTO book VALUES('73', 'L Eveil', 'Brenda K Davies', '2012', 'Fantasy Romance', ' Traumatisee par son passe et luttant pour en sortir, Sera a passe les trois dernieres annees du college a se cacher du monde et a se contenter de rester dans cette voie. Une rencontre fortuite avec Liam brise son monde abrite, la laissant stupefaite et ebranlee par les sentiments etranges et les emotions qu il emerge en elle, des sentiments qu elle n a jamais pense qu elle eprouverait et qui l effrayer dans leur intensite. Tenant un secret sombre et mortel, Liam sait qu il doit rester loin de Sera; Qu il ne lui fera que plus de mal, mais il est irresistiblement attire vers elle et incapable de se priver du plaisir que seule elle peut lui apporter. Mais quand leur passe entre en collision avec leur present, et que la vraie nature de Liam se revele, sera-t-elle suffisante pour l amour de l un pour l autre, ou sera-t-elle dechiree a jamais?', '1', '351', 'numerique', '2017');
INSERT INTO book VALUES('74', 'Les Vampires Argeneau, T1 En-cas d urgence', 'Lynsay Sands', '2011', 'Fantasy Romance', ' Lissianna est une vampire. Jusque la tout va bien. Sauf qu elle a la phobie du sang. C est ballot !
Cela fait des siecles que Lissianna cherche son ame soeur. Quand elle decouvre un homme seduisant dans son lit, elle se dit qu il pourrait tout a fait lui convenir Mais pour l heure, un probleme plus urgent la tracasse : elle
s evanouit a la vue du sang Handicap bien agacant pour un vampire. Pour ne rien arranger, le cou de ce garcon lui
met l eau a la bouche. Quelle femme, vampire qui plus est, saurait rester de marbre devant pareil festin ?', '1', '416', 'numerique', '2017');
INSERT INTO book VALUES('75', 'Game of Thrones T1 Le Trone de Fer', 'George R R Martin', '2001', 'Fantasy', ' Apres avoir tue le monarque dement Aerys II Targaryen, Robert Baratheon est devenu le nouveau souverain du royaume des Sept Couronnes.
Tandis qu en son domaine de Winterfell, son fidele ami le duc Eddard Stark rend paisiblement la justice. Mais un jour, le roi Robert lui rend visite, porteur de sombres nouvelles : le trone est en peril. Stark, qui s est toujours tenu eloigne des affaires du pouvoir, doit alors abandonner les terres du Nord pour rejoindre la cour et ses intrigues.
L heure est grave, d autant qu au-dela du Mur qui protege le royaume depuis des siecles, d etranges creatures rodent.', '1', '542', 'papier/numerique', '2017');
INSERT INTO book VALUES('76', 'Game of Thrones T2 Le Donjon Rouge', 'George R R Martin', '2001', 'Fantasy', ' Comment Lord Eddard Stark, seigneur de Winterfell, Main du Roi, gravement blesse par traitrise, et par la meme plus que jamais a la merci de la perfide reine Cersei ou des imprevisibles caprices du despotique roi Robert, aurait-il une chance d echapper a la nasse tissee dans l ombre pour l abattre ? Comment, arme de sa seule et inebranlable loyaute, cerne de toutes parts par d abominables intrigues, pourrait-il a la fois survivre, sauvegarder les siens et assurer la perennite du royaume ? Comment ne serait-il pas voue a etre finalement broye dans un engrenage infernal, alors que Catelyn, son epouse, a mis le feu aux poudres en s emparant du diabolique nain Tyrion, le frere de la reine ? ', '1', '512', 'papier/numerique', '2017');
INSERT INTO book VALUES('77', 'Game of Thrones T3 La Bataille des Rois', 'George R R Martin', '2002', 'Fantasy', ' Le roi Robert Baratheon est mort, son ami Eddard Stark a ete execute. La dynastie Baratheon n aura dure qu une generation, et la paix plusieurs fois centenaire qui regissait le Royaume des Sept Couronnes a vole en eclats. Joffrey, le batard illegitime, se terre dans sa capitale, les freres de Robert rallient des troupes a leurs bannieres, le fils de Ned a leve son armee et crie vengeance, des pirates razzient les cotes et des brigands pillent les campagnes', '1', '355', 'papier/numerique', '2017');
INSERT INTO book VALUES('78', 'Game of Thrones T4 L Ombre Malefique', 'George R R Martin', '2002', 'Fantasy', ' Plonge dans le chaos, le royaume des Sept couronnes est en proie a une formidable pandemie de violence, les heritiers du souverain defunt se disputent le trone dans d apres et sanglants combats. Et les puissants seigneurs, rallies aux diverses causes, negligent tout egard pour le peuple, qui supporte souffrances et famine. Les ennemis jures Catelyn et Tyrion fourbissent chacun leurs armes, Catelyn Stark rejoint Renly Baratheon, a la tete des forces de Hautjardin et accalmie, tandis que Tyrion Lannister durdit de nouvelles alliances et prepare Port-Real a repousser le futur siege, mais un nouveau peril se profile : une ombre qui plane, frappe les rois et renverse les citadelles', '1', '388', 'papier/numerique', '2017');
INSERT INTO book VALUES('79', 'Game of Thrones T5 L Invincible Forteresse', 'George R R Martin', '2002', 'Fantasy', ' Le denouement est proche. Car il ne reste que deux pretendants au trone des Sept Couronnes : Joffrey, le heraut du clan des Lannister, retranche a Port-Real, et Stannis Baratheon, qui a masse ses navires aux abords de la capitale en vue de l assaut final. Celui qui s en rendra maitre deviendra le veritable souverain du royaume. Il revient a Tyrion Lannister, le  Lutin Hai de tous - aussi bien de ses ennemis que de ses allies - de preparer activement la defense de l invincible forteresse. Pour cela, il a elabore un plan machiavelique afin de defaire le seigneur de Peyredragon et ses troupes. Un plan que seul son cerveau demoniaque et sa volonte de fer peuvent mettre en Å“uvre... ', '1', '409', 'papier/numerique', '2017');
INSERT INTO book VALUES('80', 'Game of Thrones T6 Les Brigands', 'George R R Martin', '2003', 'Fantasy', ' Le jeune et inconsequent roi Joffrey semble bien installe sur le trone de fer. L usurpateur Baratheon est mort, l armee de son frere Stannis a ete defaite devant Port-Real et le souverain Robb se retrouve depossede de ses propres terres. Joffrey n a pourtant participe a aucune bataille. Il doit ces succes au courage de son oncle Tyrion et a la ruse de son grand-pere Tywin. C est un roi velleitaire, lache et cruel qui s apprete donc a regner sur les Sept Couronnes. Toutes les forces en presence n ont cependant pas dit leur dernier mot. La ou les epees n ont pu l emporter, la puissance de la magie reussira-t-elle ?', '1', '350', 'papier/numerique', '2017');
INSERT INTO book VALUES('81', 'Game Of Thrones T7 L Epee de feu', 'George R R Martin', '2003', 'Fantasy', ' Les sept couronnes sont exsangues. Le royaume panse ses plaies. Les guerres ont vide les campagnes, les epidemies ont ruine les recoltes et les pillards ecument les terres devastees. Pourtant il y a toujours autant de pretendants qui briguent la couronne : chacun dans son repaire echafaude des strategies. Les Lannister multiplient les alliances fragiles, Stannis Baratheon se refugie toujours davantage dans le culte de R hllor, le maitre de la lumiere, et Robb Stark soupire apres son fief en lambeaux. Mais d autres ennemis se massent aux frontieres, loin dans le nord. Et, pendant que les puissants avancent leurs pions, les faibles tentent de survivre', '1', '319', 'papier/numerique', '2017');
INSERT INTO book VALUES('82', 'Game Of Thrones T8 Les Noces Pourpres', 'George R R Martin', '2004', 'Fantasy', ' Le temps des batailles est revolu. Le fier royaume des Sept Couronnes n est plus qu un champ de ruines. Les quelques pretendants qui s opposent encore nouent alliances et accords par des mariages arranges et sans amour. Seuls les plus subtils, les plus retors - et parfois les plus laches - l emporteront...
Et pendant ce temps, par-dela les mers, loin dans les Terres brÃ»lees, Daenerys, derniere descendante de la lignee des Targaryen, conquiert un gigantesque empire dans l espoir de restaurer l antique puissance de Valyria et de ses dragons.', '1', '410', 'papier/numerique', '2017');
INSERT INTO book VALUES('83', 'Game Of Thrones T9 La loi du regicide', 'George R R Martin', '2004', 'Fantasy', ' Les Sept Couronnes, desolees et exsangues, sont enfin reunies sous une meme banniere : celle du roi Stannis Baratheon. Pourtant, la menace gronde.
Au nord, le Mur est assailli par les Sauvageons. S ils le franchissent, les forces de l hiver balaieront tout sur leur passage.
Face a ce danger se dresse, impassible, la Garde de Nuit, dernier rempart contre le froid et la mort, fidele au poste mais tellement diminuee : il ne reste qu une poignee d hommes fatigues, desabuses, parmi lesquels Jon, le batard des Stark.
Tandis que, dans la tourmente, le nain Tyrion, seul contre tous, essaie de se disculper d un regicide qu il n a pas commis...', '1', '356', 'papier/numerique', '2017');
INSERT INTO book VALUES('84', 'Game Of Thrones T10 La Chaos', 'George R R Martin', '2007', 'Fantasy', ' Cersei, fidèle à elle-même, ourdit de nouveaux plans machiavéliques pour garder la bride sur Lannister, ce qui rendent délicat l assassinat de Tywin et la fuite du nain Tyrion, son fils et meurtrier présumé.
Au Mur, Samwell Tarly se voit confier par Jon Snow une mission qui l enverra au-delà des mers. Tandis que Brienne, la pucelle de Torth, poursuit sa quête de Sansa Stark, la sœur de cette dernière, Arya, prend le voile noir de l ordre du dieu multiface, à Braavos.
Et la situation n est guère plus reposante dans les îles de fer, où la maison Greyjoy doit gérer une succession à tout le moins contestée.', '1', '395', 'papier/numerique', '2017');
INSERT INTO book VALUES('85', 'Nos Infinis Chaos', 'Alfreda Enwy', '2017', 'Romance', ' Il sourit, son regard se posa sur mes lèvres. Il les dévorait des yeux. Oh, non... seigneur, non ! Pas ça. Les baisers, jamais. Surtout pas après un tel rêve, surtout pas après avoir revu ça ce soir... ? Ne m embrasse pas, murmurai-je. Ne cherche pas à m embrasser, Nate. Jamais. » Dylan a vécu un grave traumatisme dans son adolescence, depuis lors, elle fait ce qu elle peut pour se reconstruire. En débarquant à San Francisco, elle compte bien reprendre sa vie en main : poursuivre son entraînement au sport de combat, obtenir une licence de management, et, surtout, garder ses distances avec la gent masculine ? ses lèvres n embrasseront plus jamais celles de personne. Plus jamais. À moins que la rencontre de Nate, séduisant boxeur au passé sombre, et de son fils de 4 ans, aussi charmant que son père, ne vienne perturber cette dernière règle. Alors que leurs chemins ne cessent de se croiser, Dylan sent son coeur et son corps s éveiller, et ses troubles passés la hanter de nouveau.', '1', '268', 'numerique', '2017');
INSERT INTO book VALUES('86', 'Game of Thrones T11 Les Sables de Dorne', 'George R R Martin', '2007', 'Fantasy', ' Les têtes de nains, tranchées ont beau s accumuler sur le parvis de Castral-Roc, celle de Tyrion - meurtrier présumé de Tywin Lannister, son père - semble toujours solidement juchée sur ses deux épaules. Sa sœur Cersei, désormais régente, ne sait plus qui elle doit haïr le plus : lui ou la petite reine, Margaery, intriguante de basse-cour qui est parvenue à lui ravir le cœur du futur roi, son fils.
Ses manœuvres ont beau être cousues de fil blanc, son joli minois et ses nombreux alliés font d elle une rivale avec qui il faut compter. Pour autant, Cersei a encore quelques vilains tours dans son sac : ce n est pas aux vieilles lionnes que l on apprend à mordre', '1', '386', 'papier/numerique', '2017');
INSERT INTO book VALUES('87', 'Breaking my heart', 'Alfreda Enwy', '2017', 'Romance', ' Elle a renoncé à l amour ; il refuse de renoncer à elle...
Professeur d art à l université, Conrad enchaîne les aventures sans lendemain. À 32 ans, il est en pleine remise en question : il aimerait trouver sa muse, celle qui rallumera chez lui la flamme créatrice, celle auprès de laquelle il se réveillera chaque matin. Quand il rencontre Samantha, il tombe instantanément sous son charme. Cette femme le subjugue, le fascine, et il devine qu il lui plaît ; pourquoi s obstine-t-elle alors à le repousser ?
Depuis ce diagnostic qui a bouleversé sa vie, Samantha n est plus la même. Si sa maladie l a forcée à reprendre sa vie en main et à revoir ses priorités, ses cicatrices lui rappellent sans cesse la trahison de son propre corps ; un corps qui est devenu un étranger. Et si elle-même ne parvient pas à s accepter, comment un homme pourrait-il l aimer ?', '1', '303', 'numerique', '2017');
INSERT INTO book VALUES('88', 'Royal Saga T1 Commande Moi', 'Geneva Lee', '2016', 'Romance', ' Clara Bishop est une femme moderne. Brillante jeune diplômée, introvertie et échaudée par un passé amoureux catastrophique, elle est bien décidée à faire de sa carrière un succès. Elle accepte un jour de suivre sa colocataire à une réception huppée à laquelle participe tout le gotha et rencontre un bel et mystérieux inconnu au charme ravageur au détour d un couloir. 
Quelle n est pas sa surprise lorsqu elle découvre quelques jours plus tard à la une de tous les journaux à scandale une mauvaise photo floue de leur furtif baiser. Elle a embrassé le Prince héritier Alexander de Cambridge et il veut la revoir... Prince d accord mais surtout bad boy ! Pas prince charmant pour deux sous. Il contrôle, il exige. Il est dangereux. Et elle n arrive pas à lui dire non', '1', '340', 'numerique', '2017');
INSERT INTO book VALUES('89', 'Royal Saga T2 Captive moi', 'Geneva Lee', '2016', 'Romance', ' Je lui ai donné mon corps et il a pris mon âme.
Alexander a le monde à ses pieds et j étais à genoux devant lui, jusqu à ce que nos secrets déchirent notre couple.
Je devrais garder mes distances. Je devrais partir en courant.
Mais je suis accro... à sa présence, au plaisir qu il me procure, mais aussi à la douleur.
Il m avait prévenue, je connaissais son côté sombre, son passé. Mais moi aussi, j ai ma part d ombre. Ensemble, nous vaincrons nos démons... si avant, nous ne nous détruisons pas.
Clara Bishop a le cœur brisé de sa séparation avec Alexander, le Prince de Cambridge. Elle se réfugie dans le travail sans pouvoir l oublier, mais il lui est impossible de vivre pleinement sans lui. 
Quant elle découvre qu Alexander cherche à la retrouver, elle se décide à accepter une relation avec lui, quelle qu elle soit, car elle ne peut vivre sans lui. Mais accepter de vivre avec Alexander, c est accepter de lutter contre ses démons, accepter sa domination, ses secrets, à moins que.', '1', '259', 'numerique', '2017');
INSERT INTO book VALUES('90', 'Royal Saga T3 Couronne Moi', 'Geneva Lee', '2016', 'Romance', ' Notre amour est fait d extase et de douleur, de renaissance et de destruction, de lumière et d ombres. Je m agrippe à lui, aux réponses que j ai trouvées dans ses bras, je n ai plus peur de ce que l avenir nous réserve. Je sais que nous pourrons y faire face, ensemble.
Alexander, Prince de Cambridge, a décidé que sa passion pour Clara Bishop devait être révélée au grand jour et se concrétiser par un mariage et Clara a dit oui.
Ce qui devrait être une période heureuse, se révèle extrêmement difficile. Les démons qui rôdent autour d eux n en ont pas fini de projeter leur ombre noire et d essayer d empêcher ce mariage : Le Roi cherche tous les moyens pour empêcher que Clara monte sur le trône. Georgia, l ex perverse d Alexander joue un rôle aussi malsain que ses relations avec les hommes. Quant à Daniel, l ex de Clara, sa folie va-t-elle l amener à la plus grande des extrémités ? ', '1', '260', 'numerique', '2017');
INSERT INTO book VALUES('91', 'Royal Saga T4 Cherche moi', 'Geneva Lee', '2017', 'Romance', ' L histoire de Belle commence dans cette quatrième et captivante édition de la série best-seller du New York Times.
Je me suis faite une promesse : pas d hommes. Pas de romance. Pas d attentes à propos d un prince qui ne viendra pas. Parce que certaines filles n ont pas le droit aux \" après \".
Certaines filles ont seulement droit à des cœurs brisés.
C est pourquoi je dois rester loin de lui. Il est vil, arrogant, autoritaire. Je ne lui fais pas confiance.
Mais certains hommes entrent dans votre sang - juste sous votre peau. Mais vous ne pouvez pas obtenir tout ce que vous voulez de certains hommes.
Certains hommes dont vous avez envie ...
Trahie par l homme que sa famille lui avait choisi, Belle se retrouve seule et sans travail. ', '1', '240', 'numerique', '2017');
INSERT INTO book VALUES('92', 'Off Campus The Deal', 'Elle Kennedy', '2016', 'Romance', ' Hannah est une très bonne élève et elle a un don incroyable pour le chant.
Mais quand il s agit d hommes et de séduction, elle perd tous ses moyens. Garrett est la star de l équipe de hockey de l université, mais ses résultats scolaires ne sont pas à la hauteur et il risque de perdre sa place dans l équipe. Ils vont passer un drôle d accord. Elle lui donne des cours et il l aide à séduire le quaterback de l équipe de football.
Cet arrangement original va-t-il changer leur vie ?', '1', '331', 'numerique', '2017');
INSERT INTO book VALUES('93', 'Off Campus The Mistake', 'Elle Kennedy', '2016', 'Romance', ' C est un joueur et pas uniquement sur le terrain...
John Logan est une star de l équipe de Hockey ce qui lui permet d avoir toutes les filles qu il veut.
Mais derrière ses sourires de tueurs et son charme ravageur, se cache un être blessé et inquiet de son avenir qui ne s annonce pas tout rose.
Quand il rencontre Grace, étudiante en première année, et il se dit qu elle sera la fille idéale pour lui changer les idées. Mais Grace fini par le repousser à cause de son comportement et John va devoir se mettre en quatre s il veut la récupérer.
Grace n est plus la jeune fille timide et innocente du début de l année, et elle compte bien lui faire payer son erreur. John va devoir élever son niveau de jeu.', '1', '295', 'numerique', '2017');
INSERT INTO book VALUES('94', 'Off Campus The Score', 'Elle Kennedy', '2016', 'Romance', ' Allie Hayes est en mode crise. Elle n a toujours pas la moindre idée de ce qu elle va faire après avoir obtenu son diplôme, pourtant la date fatidique approche à grands pas. Et comme si cela ne suffisait pas, elle tente de se remettre d une rupture qui lui a brisé le coeur. Ce qui est certain, c est que la solution à ses problèmes ne passe pas par une histoire sauvage avec la star de hockey Dean Di Laurentis ! Et pourtant, il est tellement difficile de lui résister. Mais Allie a décidé que même si son avenir est incertain, une seule chose est sûre, elle ne sera pas le prochain coup d un soir du hockeyeur.Il va falloir qu il en fasse un peu plus que d habitude pour la faire céder. Dean obtient toujours ce qu il veut. Des filles, des bonnes notes, des filles, la gloire, des filles... C est un homme à femmes, et il n a jamais rencontré une fille qui reste insensible à son charme. Jusqu à Allie. En une nuit, la blonde fougueuse a fait basculer son petit monde. Et elle lui dit qu elle veut être son amie ! Non. C est lui qui décide du déroulement des choses et il n est pas prêt à bousculer sa façon de vivre. Cette fille-là va faire tourner la tête du volage Dean, au point qu il se demande s il n est pas temps d arrêter d enchaîner les amourettes pour se jeter dans le grand amour.', '1', '310', 'numerique', '2017');

